website/auth.py
# This File Contain Routes That Have Authentication, Like Login, Logout
from flask import Blueprint, current_app, render_template, request, flash, redirect, url_for, session,jsonify
from website import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required,logout_user, current_user
from flask_mail import Mail, Message
from .models import User
from random import *
from datetime import datetime, timedelta
import json
import os

auth = Blueprint('auth', __name__)

# @@@@@@@@@@@@@@ Sign Up Page @@@@@@@@@@@@@@
@auth.route('/sign-up', methods=['GET', 'POST'])
def signUp():
    if request.method == 'POST':
        # Get Inputs
        f_name = request.form.get('f_name')
        l_name = request.form.get('l_name')
        age = request.form.get('age')
        gender = request.form.get('gender')
        email = request.form.get('email')
        password = request.form.get('password')
        password2 = request.form.get('password2')

        # Check If Already Exist 
        user = User.query.filter_by(email=email).first()
        if user: 
            flash("لديك حساب بالفعل! قم بتسجيل الدخول!", category='error')
        elif not checkSignUp(f_name, l_name, age, gender, email, password, password2):
            flash("أكمل البيانات بالطريقة الصحيحة", category="error")
        else:
            # Start Email Verification
            otp_num = randint(1000, 9999)
            session['otp_num'] = otp_num
            session['otp_time'] = datetime.now()
            session['temp_user'] = {
                'f_name': f_name,
                'l_name': l_name,
                'age': age,
                'gender': gender,
                'email': email,
                'password': generate_password_hash(password)
            }

            # Flask-email Configuration
            current_app.config['MAIL_SERVER'] = 'smtp.gmail.com'
            current_app.config['MAIL_PORT'] = 587
            current_app.config['MAIL_USE_TLS'] = True
            current_app.config['MAIL_USE_SSL'] = False
            current_app.config['MAIL_USERNAME'] = os.environ.get('MAIL_USERNAME')
            current_app.config['MAIL_PASSWORD'] = os.environ.get('MAIL_PASSWORD')

            mail = Mail(current_app)

            # Send OTP Message To User
            msg = Message(subject='تطبيق ملهم', sender='mulhem2025gp@gmail.com', recipients=[email])
            msg.html = f'''
                <html>
                    <body style="text-align:center">
                        <h1>رمز التحقق</h1>
                        <p>رمز التحقق الخاص بك هو: <strong>{otp_num}</strong></p>
                    </body>
                </html>
            '''
            mail.send(msg)

            flash("تم إرسال رمز التحقق إلى بريدك الإلكتروني. يرجى إدخال الرمز.", category='info')
            return redirect(url_for('auth.verify'))
        
    return render_template('/auth/sign-up.html', user=current_user)

# Varify Sign Up Inputs
def checkSignUp(f_name, l_name, age, gender, email, password, password2):
    # Name
    if len(f_name) < 2 or len(f_name) > 30 :
        flash("الاسم الأول يجب أن يتكون من 3 إلى 30 حرفاً", category='error')
    elif len(l_name) < 2 or len(l_name) > 30:
        flash("الاسم الأخير يجب أن يتكون من 3 إلى 30'حرفاً'", category='error')
    # Age
    elif not age:
        flash("يرجى ادخال عمرك", category='error')
    elif int(age) < 8 or int(age) > 10:
        flash("عذرًا، هذا الموقع غير مخصص لفئتك العمرية", category='error')
    # Gender
    elif not gender:
        flash("يرجى اختيار الجنس", category='error')
    # Email
    elif not email:
        flash("الإيميل لا يمكن أن يكون فارغًا", category='error')
    # Password
    elif not password:
        flash("كلمة المرور لا يمكن أن تكون فارغة", category='error')
    elif len(password) < 8:
        flash("يجب أن لا تقل كلمة المرور عن 8 أحرف", category='error')
    elif len(password) > 128:
        flash("يجب أن لا تزيد كلمة المرور عن 128 حرفاَ", category='error')
    elif not any(char.isupper() for char in password):
        flash("يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل", category='error')
    elif not any(char.islower() for char in password):
        flash("يجب أن تحتوي كلمة المرور على حرف صغير واحد على الأقل", category='error')
    elif not any(char.isdigit() for char in password):
        flash("يجب أن تحتوي كلمة المرور على رقم واحد على الأقل", category='error')
    elif any(char.isspace() for char in password):
        flash("يجب أن لا تحتوي كلمة المرور على مسافات", category='error')
    elif password != password2:
        flash("كلمة المرور غير متطابقة، حاول مجددا", category='error')
    else: 
        return True
    
# Verify Email Page
@auth.route('/verify', methods=['GET', 'POST'])
def verify():
    if request.method == 'POST':
        entered_otp = request.form.get('otp')
        otp_num = session.get('otp_num')  # الحصول على رمز التحقق من الجلسة
        otp_time = session.get('otp_time')  # الحصول على وقت التحقق من الجلسة
        temp_user = session.get('temp_user')  # الحصول على بيانات المستخدم المؤقتة

        # التحقق من وجود otp_num و otp_time و temp_user
        if not otp_num or not otp_time or not temp_user:
            flash("لم يتم العثور على رمز التحقق أو بيانات المستخدم. يرجى إعادة المحاولة.", category='error')
            return redirect(url_for('auth.signUp'))

        # التأكد من أن كلاً من datetime.now() و otp_time هما نفس النوع
        if isinstance(otp_time, datetime):
            # إذا كانت otp_time تحتوي على معلومات المنطقة الزمنية (aware), نقوم بإزالة المنطقة الزمنية منها
            otp_time = otp_time.replace(tzinfo=None)

        # الآن قارن بين datetime.now() و otp_time
        if datetime.now() > otp_time + timedelta(hours=1):  # انتهاء صلاحية بعد ساعة
            flash("رمز التحقق منتهي الصلاحية. يرجى إعادة المحاولة.", category='error')
            session.pop('otp_num', None)
            session.pop('otp_time', None)
            session.pop('temp_user', None)
            return redirect(url_for('auth.signUp'))

        # التحقق من صحة رمز التحقق
        if str(entered_otp) == str(otp_num):  # مقارنة الرمز المدخل مع الرمز المرسل
            # حفظ المستخدم في قاعدة البيانات بعد التحقق
            new_user = User(
                first_name=temp_user['f_name'],
                last_name=temp_user['l_name'],
                age=temp_user['age'],
                gender=temp_user['gender'],
                email=temp_user['email'],
                password=temp_user['password']
            )
            db.session.add(new_user)
            db.session.commit()

            # إزالة البيانات المؤقتة من الجلسة
            session.pop('otp_num', None)
            session.pop('otp_time', None)
            session.pop('temp_user', None)

            flash("تم التحقق بنجاح وتم إنشاء الحساب!", category='success')
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))  # توجيه المستخدم إلى الصفحة الرئيسية
        else:
            flash("رمز التحقق غير صحيح. حاول مرة أخرى.", category='error')

    return render_template('auth/verify.html')

    
# @@@@@@@@@@@@@@ Login Page @@@@@@@@@@@@@@
@auth.route('/login', methods=['GET', 'POST'])
def login():
    email = None

    if request.method == 'POST':
        # Get Inputs
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first() 
        if user: #If User Exist
            if check_password_hash(user.password, password):
                flash("تم تسجيل دخولك بنجاح", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("كلمة المرور خاطئة!", category='error')
        else: # If User Not Exist
            flash("البريد الإلكتروني الذي أدخلته غير موجود!", category='error')

    return render_template('/auth/login.html', user=current_user)

# @@@@@@@@@@@@@@ Logout Page @@@@@@@@@@@@@@
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash("تم تسجيل خروجك", category='success')
    return redirect(url_for('views.home'))



# @@@@@@@@@@@@@@ Profile Page @@@@@@@@@@@@@@
@auth.route('/profile')
@login_required
def profile():
    return render_template('auth/profile.html', user=current_user)

# Update Profile
@auth.route('/update_profile')
@login_required
def update_profile():
    return render_template('auth/update_profile.html', user=current_user)

# Update Profile DataBase
@auth.route('/update_user_profile', methods=['POST'])
@login_required
def update_user_profile():
    data = request.json
    if not data:
        return jsonify({"response": "Invalid request, no data provided."}), 400

    first_name = data.get('first_name', '')
    last_name = data.get('last_name', '')
    age = data.get('age', '')
    gender = data.get('gender', '')
    email = data.get('email', '')
    password = data.get('password', None)

    user = User.query.filter_by(id=current_user.id).first()
    if not user:
        return jsonify({"response": "User not found."}), 400

    # التحقق من وجود البريد الإلكتروني مسبقًا مع استثناء المستخدم الحالي
    if email and email != user.email:
        email_exists = User.query.filter(User.email == email, User.id != current_user.id).first()
        if email_exists:
            return jsonify({"response": "البريد الإلكتروني مستخدم بالفعل"}), 400

    # تحديث البيانات
    user.first_name = first_name
    user.last_name = last_name
    user.age = age
    user.gender = gender
    user.email = email

    # تحديث كلمة المرور إذا كانت جديدة
    if password and password != "***********":

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="/static/images/logo.png">
    <!-- Google Fonts Links -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <!-- Mulhem Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
    <!-- Font Awesome Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Css Links -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% block styles %}{% endblock %}
</head>
<body>
  <div class="gradian-background">
      <!-- Start Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid container">
              <!-- شعار التطبيق -->
              <a class="navbar-brand me-0 d-flex align-items-center" href="/">
              <img src="/static/images/logo.png" alt="Logo" width="80" height="60">
              مُـــلـــهِـــمْ 
              </a>
              <!-- زر التبديل (للعرض على الأجهزة الصغيرة) -->
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <!-- روابط التنقل -->
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="/"><i class="fa-solid fa-house"></i> الصفحة الرئيسية</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link {% if request.path == '/reading/our_library' %}active{% endif %}" href="/reading/our_library"><i class="fa-solid fa-book-open-reader"></i> القراءة</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link {% if request.path == '/writing/writing-types' %}active{% endif %}" href="/writing/writing-types"><i class="fa-solid fa-pencil"></i> الكتابة</a>
                  </li>
                  {% if current_user.is_authenticated %}
                  <!-- Show Link If User Logged In -->
                  {% endif %}
                  <li class="nav-item">
                      <a class="nav-link {% if request.path == '/activities/all_activities' %}active{% endif %}" href="/activities/all_activities"><i class="fa-solid fa-person-chalkboard"></i> أنشطة تعليمية</a>
                  </li>
                  {% if current_user.is_authenticated %}
                  <!-- Show Link If User Logged In -->
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/writing/user-stories' %}active{% endif %}" href="/writing/user-stories"><i class="fa-solid fa-book"></i> قصصي</a>
                  </li>
                  {% endif %}
                  <li class="nav-item">
                    <a class="nav-link {% if request.path == '/help' %}active{% endif %}" href="/help"><i class="fa-solid fa-circle-question"></i> مركز المساعدة</a>
                  </li>
              </ul>
              
              </div>
              <div class="sign-log d-flex align-items-center">
                {% if current_user.is_authenticated %} <!-- Show Those Links If User Logged In -->
                <a class="profile ms-3" href="{{ url_for('auth.profile') }}" alt="المساعدة"><button type="button"><i class="fa-solid fa-circle-user"></i></button></a>
                <a href="{{ url_for('auth.logout') }}"><button type="button">تسجيل الخروج</button></a>
                {% else %} 
                <a href="{{ url_for('auth.signUp') }}" class="ms-3"><button type="button">إنشاء حساب</button></a>
                <a href="{{ url_for('auth.login') }}"><button type="button">تسجيل دخول</button></a>
                {% endif %} 
              </div>
          </div>
      </nav>
      <!-- End Navbar -->

       <!-- Start Flash Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %} <!-- If There Is Message -->
    <div id="flash-messages">
        {% for category, message in messages %}
            {% if category == 'error' %} 
            <div class="alert alert-danger alert-dismissible fade show" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true"></span></button>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}
    <!-- End Flash Messages -->

      {% block landing %}
      {% endblock %}
    </div>
   
    
    {% block body %}
    {% endblock %}

    <!-- Start Footer -->
    <footer>
      <div class="wavy"></div>
      <div class="row container justify-content-around align-items-center mx-auto my-4 mt-1">
        <div class="col-md-3">
          <div class="footer-menu">
            <img src="/static/images/logo.png" alt="logo" width="100" height="100">
            <h5 class="mt-3"> مُــلــهِــمْ - حيث تبدأ حكايات الأطفال، ونمنحهم الإلهام لخلق قصصهم الخاصة.</h5>
          </div>
        </div>


        <div class="col-md-3">
          <div class="footer-menu">
            <a href="#" class="nav-link contact">تواصل معنا </a>
            <div class="social-links">
              <ul class="d-flex list-unstyled gap-2 mb-0 p-0 ">
                <li class="social">
                  <a href="#"><img src="/static/images/Facebook icon.png" alt="Facebook" width="25" height="25">   
                  </a>
                </li>
                <li class="social">
                  <a href="#"><img src="/static/images/Twitter-icon.png" alt="Twitter" width="25" height="25"> 
                </li>
                <li class="social">
                  <a href="#"><img src="/static/images/instagram-logo.png" alt="Instagram" width="25" height="25"> 
                </li>
                <li class="social">
                  <a href="#"><img src="/static/images/whatsapp-icon.png" alt="whatsapp" width="25" height="25"> 
                </li>
                <li class="social">
                  <a href="#">
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="footer-menu">
            <ul class="menu-list list-unstyled">
              <li class="menu-item">
                <a href="../activities/all_activities" class="nav-link">أنشطة الكتابة</a>
              </li>
              <li class="menu-item">
                <a href="../reading/our_library" class="nav-link">اقرأ قصة</a>
              </li>
              <li class="menu-item">
                <a href="../writing/story-generator" class="nav-link">انشئ قصة</a>
              </li>
              <li class="menu-item">
                <a href="../writing/self-writing" class="nav-link">اكتب قصة</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

<div id="footer-bottom">
  <div class="container">
    <hr class="m-0">
    <div class="row mt-3">
      <div class="col-md-6 mx-auto text-center copyright">
        <p class="secondary-font mb-0">© 2024 mulhem. All rights reserved.</p>
      </div>
      
    </div>
  </div>
</div>

</footer>
    <!-- End Footer -->

    <!-- Answers Audios  -->
    <audio id="confetti-sound-right" src="../static/audio/wow.aac"></audio>
    <audio id="sound-wrong" src="../static/audio/ohh.wav"></audio>
    <audio id="clap-sound" src="../static/audio/clap.wav"></audio>
    <!-- Sweet Alert2 Link -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Bootstrap Link -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Main js File -->
    <script src="../static/js/main.js"></script>
    <script type="module" src="../static/js/main2.js"></script>
    <!-- JS Links -->
    {%block script%}
    {%endblock%}
</body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}الصفحة الرئيسية{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}
{% block landing %}
<!-- Landing -->
<div class="home-landing">
  <div class="content container d-flex justify-content-between">
    <!-- If User Logged In -->
    {% if user.is_authenticated %}
      <div class="text thought w-50">
        {% if user.gender == "أنثى"%}
        <h2 class="mb-4 mt-2">مرحبًا بكِ يا {{user.first_name}} في عالم <span>مُلهِم</span>!</h2>
        <p class="w-75 mx-auto"><p> استمتعي بكتابة قصصك، تطوير مهاراتكِ الإبداعية، <br>واكتشاف عالم القراءة وأنشطة الكتابة الممتعة.<br> قصتكِ بانتظار أن تُكتب!</p></p>
        {% else %}
        <h2 class="mb-4 mt-2">مرحبًا بك يا {{user.first_name}} في عالم <span>مُلهِم</span>!</h2>
        <p class="w-75 mx-auto"><p> استمتع بكتابة قصصك، تطوير مهاراتك الإبداعية، <br>واكتشاف عالم القراءة وأنشطة الكتابة الممتعة.<br> قصتك بانتظار أن تُكتب!</p></p>
        {% endif %}
      </div>
      <!-- If User Not Logged In -->
      {% else %}
      <div class="text thought un-loged w-50">
        <h2 class="mb-4 mt-2">مرحبا بك في عالم <span>مُلهِم</span></h2>
        <p class="descrip">أنا <span>مُلهِم</span>، دليلك إلى عالم الكتابة والإبداع! هنا يمكنك استكشاف قصص مشوقة ومتنوعة، تحويل أفكارك إلى حكايات رائعة، وتعلّم أساسيات الكتابة بأسلوب ممتع وسهل.</p>      
        <p class="mb-2">سجل دخولك الآن لتبدأ رحلتك الإبداعية!</p>
        <div class="account-buttons">
          <a href="{{ url_for('auth.signUp') }}"><button type="button" class="button main-button ms-1">إنشاء حساب</button></a>
          <a href="{{ url_for('auth.login') }}"><button type="button" class="button main-button">تسجيل الدخول</button></a>
        </div>
      </div>
      {% endif %}
      <!-- Mulhem -->
      <div class="img position-relative">
      <img src="../static/images/mulhem-hi.png" alt="مُلهِم" class="mulhem">
    </div>
  </div>
  <div class="wavy"></div>
</div>
{% endblock %}

{% block body %}
<div class="home">
  <div class="section-1 my-5">
  <div class="line-container mb-3">
    <div class="line"></div>
    {% if user.is_authenticated and user.gender == "أنثى" %}
      <span class="line-text"> اقرئي القصص وعدّليها</span>
      {% else %}
      <span class="line-text"> اقرأ القصص وعدّلها</span>
    {% endif %}
    <div class="line"></div>
  </div>
  <div class ="section-container">
    <div class="story-box our" id="7">
      <a>
          <img src="/static/images/التمرة الضائعة.jpeg" alt="التمرة الضائعة"  height="270px"  width="250px"   max-width="100%" >
          <p>التمرة الضائعة</p>
      </a>
    </div>
  <div class="story-box our" id="9">
    <div calss=" img-e">
    <a>
        <img src="/static/images/علاء الدين.jpeg" alt="علاء الدين"  height="270px"  width="250px"  >
        <p>علاء الدين و المصباح السحري</p>
    </a>
  </div> 
  </div>
  <div class="story-box">
    <a href="../reading/our_library" target="_blank">
        <img class="img-icon" src="/static/images/open-book.png" alt=" اقرأ المزيد "  height="270px"  width="250px"   max-width="100%" >
        {% if user.is_authenticated and user.gender == "أنثى" %}
          <p>اقرئي المزيد </p>
          {% else %}
          <p>اقرأ المزيد </p>
        {% endif %}
    </a>
  </div>
  </div>
  </div>
    </section>
    
    
  <div class="line-container mb-3">
    <div class="line"></div>
    <span class="line-text"><i class="fa-solid fa-pencil"></i></span>
    <div class="line"></div>
  </div>
    
  <section>


  <div class="section-2 mb-5">
    <div class="section-container">
      <div class="story-box">
        <div calss=" img-e">
        <a href="../activities/all_activities" target="_blank">
          
            <img class="img-icon" src="/static/images/teacher1.png" alt=" دروس الكتابة"  height="270px"  width="250px"  >
            <p>لنتعلم أنشطة الكتابة معاً</p>
        </a>
        </div> 
      </div>
      <div class="story-box">
        <a href="/writing/story-generator" target="_blank">
          <img class="img-icon" src="/static/images/generate-icon.png" alt="  انشاء قصة "    height="270px"  width="250px"   max-width="100%" >
          {% if user.is_authenticated and user.gender == "أنثى" %}
          <p> دع مُلهِم يكتب لكِ قصة </p>
          {% else %}
          <p> دع مُلهِم يكتب لك قصة </p>
          {% endif %}
        </a>
      </div>
      <div class="story-box">
        <a href="/writing/self-writing" target="_blank">
            <img class="img-icon" src="/static/images/writing.png" alt="أبدع واكتب قصة "  height="270px"  width="250px"   max-width="100%" >
            {% if user.is_authenticated and user.gender == "أنثى" %}
            <p>أبدعي واكتبي قصة </p>
            {% else %}
            <p>أبدع واكتب قصة </p>
            {% endif %}
        </a>
      </div>
    </div>
  </div>
    </section>
</div>
<body>
{% endblock %}
{% block script %}
<script>
    // Send Reding Type (our_library) To Server
    document.querySelectorAll(".home .story-box.our").forEach(story => {
        story.addEventListener("click", async () => {
            try {
                const data = { message: ["our_library",story.getAttribute("id")] }; 
                const response = await fetch('http://127.0.0.1:5000/reading/get-reading-type', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify(data),
                });            
                if (!response.ok) {
                    throw new Error('فشل الاتصال بالخادم. حاول مرة أخرى.');
                }
                const result = await response.json();
                if (result.redirect) {
                    // إعادة التوجيه إلى الرابط المولد
                    window.open(result.redirect, '_blank');
                }
            } catch (error) {
                console.error('حدث خطأ:', error);
            }
        })
    })

</script>
{% endblock %}




